spring:
  application:
    name: servicea
  config:
    import: "optional:configserver:"
  cloud:
    config: 
      uri: http://localhost:8081/
      name: service-b
      enable: true
  profiles:
    active:prod
